services:
  - type: web
    name: ngo-platform-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URL
        sync: false          # set this manually in Render dashboard
      - key: DB_NAME
        value: ngo_db
      - key: SECRET_KEY
        generateValue: true  # Render auto-generates a secure random value
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 60
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: 30
